[package]
name = "ahlang"
version = "0.1.0"
edition = "2021"

[lib]
name = "ahlang"
path = "src/lib.rs"

[dependencies]
ariadne = "0.4.1"
chumsky = "1.0.0-alpha.4"
smol_str = "0.2.1"
thiserror = "1.0.61"

[build-dependencies]
cc = "*"
